### ISSUE TITLE
Sidebar not updating when headers change

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/mbon-docs#1]
Some of these headers no longer exist in the content. Why isn't the sidebar updating?

![image](https://user-images.githubusercontent.com/8480023/139294495-f8242d75-4926-4309-b5b5-be135818e59a.png)

**Comment by MathewBiddle** [comment]
@mwengren you mentioned the toolbars are difficult to manage in jekyll. Any advice on updating the dropdown when the headers of a document change?

**Comment by MathewBiddle** [comment]
RTFM matt! https://ioos.github.io/ioos-documentation-jekyll-skeleton/howto.html#configuring-the-side-navigation-bar

**Comment by mwengren** [comment]
Hey @MathewBiddle Yeah, if the anchor links change in any way the corresponding text in `sidebar_ioos.yml` after the `#` mark for the anchor link text will need to be updated.  I don't remember if the sidebar re-renders after you make/save an edit in local dev mode, you might have to CTRL+C and restart the server for the updates to be picked up.
